# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a013ad4b4f86c4c45e5ca32f7bd62a295ad2d38b79689a6dc70af8f314cd6af5e450a5cdd86757c9d6045bac1565b9e8faae799ee79e47f38729a7f992343c67

test:
  secret_key_base: c074bb44a48dd290c15c9ccb4919de8a1703770686c983d589ad2e57e6a26912c93bed7bc64fd1f9bf76c52529743cadbc4ba631b66bbf803e9cb55fcd452a33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
